sudo: required

services:
  - docker

language: node_js
node_js:
  "6"

before_install:
  - npm install

branches:
  only:
  - develop
  - master

after_success:
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    docker build -t "$DOCKER_IMAGE":dev .;
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
    docker push "$DOCKER_IMAGE":dev;
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t "$DOCKER_IMAGE":latest .;
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
    docker push "$DOCKER_IMAGE":latest;
    fi