FORMAT: 1A
HOST: http://wind.api.jazbelt.net/

# Wind API

Polls is a simple API allowing consumers to view polls and vote in them.

## Cross wind Collection [/xwind{?rwy_hdg,wind_hdg,wind_spd}]

### Calculate cross wind [GET]

+ Parameters

    + rwy_hdg: 5 (number, required) - Runway heading
    + wind_hdg: 30 (number, required) - Wind heading
    + wind_spd: 40 (number, required) - Wind speed

+ Response 200 (application/json; charset=utf-8)
    

    + Body
    
            {
                "speed": 16.9,
                "heading": 25
            }

## Head wind Collection [/hwind{?rwy_hdg,wind_hdg,wind_spd}]

### Calculate head wind [GET]

+ Parameters

    + rwy_hdg: 5 (number, required) - Runway heading
    + wind_hdg: 30 (number, required) - Wind heading
    + wind_spd: 40 (number, required) - Wind speed

+ Response 200 (application/json; charset=utf-8)
    

    + Body
    
            {
                "speed": 36.25,
                "heading": 25
            }